name: syncToGitee
'on':
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror with force push (git push -f)
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/027xiguapi
          dst: gitee/xiguapi027
          dst_key: '${{ secrets.GITEE_PRIVATE_KEY }}'
          dst_token: '${{ secrets.GITEE_TOKEN }}'
          static_list: pear-rec
          force_update: true
          debug: true
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: xiguapi027
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: '${{ secrets.GITEE_PASSWORD }}'
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: xiguapi027/pear-rec
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
